// frontend/src/app/components/add-product/add-product.component.ts
import { Component } from '@angular/core';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-add-product',
  standalone: false,
  templateUrl: './add-product.component.html',
  styleUrls: ['./add-product.component.css']
})
export class AddProductComponent {
  product = { name: '', price: 0, description: '', type: '', stock: 0 };

  constructor(private apiService: ApiService) {}

  addProduct(): void {
    this.apiService.addProduct(this.product).subscribe(() => {
      alert('Producto agregado exitosamente.');
    });
  }
}

<div>
    <input [(ngModel)]="product.name" placeholder="Nombre del producto" />
    <input [(ngModel)]="product.price" type="number" placeholder="Precio" />
    <input [(ngModel)]="product.description" placeholder="Descripción" />
    <input [(ngModel)]="product.type" placeholder="Tipo" />
    <input [(ngModel)]="product.stock" type="number" placeholder="Stock" />
    <button (click)="addProduct()">Agregar Producto</button>
  </div>

// frontend/src/components/AddProduct.jsx
import React, { useState } from 'react';
import axios from 'axios';

function AddProduct() {
    // Lógica del componente
}



const AddProduct = () => {
    const [product, setProduct] = useState({ name: "", type: "", price: "", description: "", stock: "" });
  
    const handleAdd = async () => {
      await axios.post("http://localhost:8000/agregar_producto", product);
      alert("Producto agregado");
    };
  
    return (
      <div>
        <h2>Agregar Producto</h2>
        <input type="text" placeholder="Nombre" onChange={(e) => setProduct({ ...product, name: e.target.value })} />
        <input type="text" placeholder="Tipo" onChange={(e) => setProduct({ ...product, type: e.target.value })} />
        <input type="number" placeholder="Precio" onChange={(e) => setProduct({ ...product, price: e.target.value })} />
        <textarea placeholder="Descripción" onChange={(e) => setProduct({ ...product, description: e.target.value })} />
        <input type="number" placeholder="Stock" onChange={(e) => setProduct({ ...product, stock: e.target.value })} />
        <button onClick={handleAdd}>Agregar</button>
      </div>
    );
  };
  
  export default AddProduct; // Exporta el componente
