// frontend/src/app/components/disable-product/disable-product.component.ts
import { Component } from '@angular/core';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-disable-product',
  standalone: false,
  templateUrl: './disable-product.component.html',
  styleUrls: ['./disable-product.component.css']
})
export class DisableProductComponent {
  productId = 0;

  constructor(private apiService: ApiService) {}

  disableProduct(): void {
    this.apiService.disableProduct(this.productId).subscribe(() => {
      alert('Producto deshabilitado.');
    });
  }
}



<div>
    <input [(ngModel)]="productId" type="number" placeholder="ID del producto" />
    <button (click)="disableProduct()">Deshabilitar Producto</button>
  </div>

// frontend/src/components/DisableProduct.jsx
import React, { useState } from 'react';
import axios from 'axios';

const DisableProduct = () => {
    const [productId, setProductId] = useState("");
  
    const handleDisable = async () => {
      await axios.delete(`http://localhost:8000/deshabilitar_producto/${productId}`);
      alert("Producto deshabilitado");
    };
  
    return (
      <div>
        <h2>Deshabilitar Producto</h2>
        <input type="text" placeholder="ID del Producto" onChange={(e) => setProductId(e.target.value)} />
        <button onClick={handleDisable}>Deshabilitar</button>
      </div>
    );
  };
