// frontend/src/app/components/update-product/update-product.component.ts
import { Component } from '@angular/core';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-update-product',
  standalone: false,
  templateUrl: './update-product.component.html',
  styleUrls: ['./update-product.component.css']
})
export class UpdateProductComponent {
  product = {id:0, name: '', price: 0, description: '', type: '', stock: 0 };

  constructor(private apiService: ApiService) {}

  addProduct(): void {
    this.apiService.updateProduct(this.product).subscribe(() => {
      alert('Producto actualizado exitosamente.');
    });
  }
}

<div>
    <input [(ngModel)]="product.id" placeholder="Id del producto" />
    <input [(ngModel)]="product.name" placeholder="Nombre del producto" />
    <input [(ngModel)]="product.price" type="number" placeholder="Precio" />
    <input [(ngModel)]="product.description" placeholder="Descripción" />
    <input [(ngModel)]="product.type" placeholder="Tipo" />
    <input [(ngModel)]="product.stock" type="number" placeholder="Stock" />
    <button (click)="updateProduct()">Actualizar Producto</button>
  </div>

// frontend/src/components/UpdateProduct.jsx
import React, { useState } from 'react';
import axios from 'axios';

const UpdateProduct = () => {
    const [productId, setProductId] = useState("");
    const [updates, setUpdates] = useState({ name: "", type: "", price: "", description: "", stock: "" });
  
    const handleUpdate = async () => {
      await axios.put(`http://localhost:8000/actualizar_producto/${productId}`, updates);
      alert("Producto actualizado");
    };
  
    return (
      <div>
        <h2>Actualizar Producto</h2>
        <input type="text" placeholder="ID del Producto" onChange={(e) => setProductId(e.target.value)} />
        <input type="text" placeholder="Nuevo Nombre" onChange={(e) => setUpdates({ ...updates, name: e.target.value })} />
        <input type="text" placeholder="Nuevo Tipo" onChange={(e) => setUpdates({ ...updates, type: e.target.value })} />
        <input type="number" placeholder="Nuevo Precio" onChange={(e) => setUpdates({ ...updates, price: e.target.value })} />
        <textarea placeholder="Nueva Descripción" onChange={(e) => setUpdates({ ...updates, description: e.target.value })} />
        <input type="number" placeholder="Nuevo Stock" onChange={(e) => setUpdates({ ...updates, stock: e.target.value })} />
        <button onClick={handleUpdate}>Actualizar</button>
      </div>
    );
  };
